{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jfl110",
    "module": "aws-base",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ohjbrnsgojcg7h5yas6otbutp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.6.7.1"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-multibindings",
          "version": {
            "requires": "4.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-dynamodb",
          "version": {
            "requires": "1.11.701"
          }
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-client",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "aws-base-0.0.1-SNAPSHOT.jar",
          "url": "aws-base-0.0.1-SNAPSHOT.jar",
          "size": 50189,
          "sha512": "14dac166d3eb9bfb1067d4e1be760cbd3b641d946f11df577cff6f719ac3258d029587bf77a9c5e4608f38ef694206e7b7ab9639b0f63d0762f26f96452edf39",
          "sha256": "70e63f39bf95f53796522fa32bfe771f3ef07bf1a7b1ef552f2f4c5958cb5928",
          "sha1": "e8564503eea2257fb9baef257b2b3bf27440a705",
          "md5": "bbc741e41c881211bd5ae2dc17822441"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.6.7.1"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-multibindings",
          "version": {
            "requires": "4.0"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-dynamodb",
          "version": {
            "requires": "1.11.701"
          }
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-client",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "aws-base-0.0.1-SNAPSHOT.jar",
          "url": "aws-base-0.0.1-SNAPSHOT.jar",
          "size": 50189,
          "sha512": "14dac166d3eb9bfb1067d4e1be760cbd3b641d946f11df577cff6f719ac3258d029587bf77a9c5e4608f38ef694206e7b7ab9639b0f63d0762f26f96452edf39",
          "sha256": "70e63f39bf95f53796522fa32bfe771f3ef07bf1a7b1ef552f2f4c5958cb5928",
          "sha1": "e8564503eea2257fb9baef257b2b3bf27440a705",
          "md5": "bbc741e41c881211bd5ae2dc17822441"
        }
      ]
    }
  ]
}
