name: Upload to AWS Lambda

on:
  workflow_dispatch:
  push:
    paths:
    - 'version.properties'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew test -Pusername=JFL110 -Ppassword=${{ secrets.GP_PUBLISH_TOKEN }}
    - name: Produce Zip
      run: ./gradlew buildZip -Pusername=JFL110 -Ppassword=${{ secrets.GP_PUBLISH_TOKEN }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Apply
      run: terraform apply -auto-approve
